import { getStrings } from "./localization/Localization";
import { createTheme, ITheme } from "office-ui-fabric-react/lib/Styling";

export enum ThemeTypes {
  Light,
  Dark,
}

/** All existing themes. The theme dropdown menu populates items in the given order, so don't change it. */
export enum Themes {
  DefaultLight = 0,
  EarthAndSky = 1,
  ContrastLight = 2,
  DefaultDark = 3,
  DeepSea = 4,
  MidnightEarth = 5,
  ContrastDark = 6,
}

export interface ISupportedTheme {
  localizedName: string;
  theme: ITheme;
  themeId: Themes;
  themeType: ThemeTypes;
}

const strings = getStrings();

/** Colors with associated themes. Note: items here are displayed in the order given below for the themes dropdown. */
export const themes: { [key in Themes]: ISupportedTheme } = {
  [Themes.ContrastDark]: {
    localizedName: strings.ThemeContrastDark,
    themeId: Themes.ContrastDark,
    themeType: ThemeTypes.Dark,
    theme: createTheme({
      palette: {
        themePrimary: "#ffea00",
        themeLighterAlt: "#0a0900",
        themeLighter: "#292500",
        themeLight: "#4d4600",
        themeTertiary: "#998c00",
        themeSecondary: "#e0ce00",
        themeDarkAlt: "#ffec19",
        themeDark: "#ffef3d",
        themeDarker: "#fff370",
        neutralLighterAlt: "#0b0b0b",
        neutralLighter: "#151515",
        neutralLight: "#252525",
        neutralQuaternaryAlt: "#2f2f2f",
        neutralQuaternary: "#373737",
        neutralTertiaryAlt: "#595959",
        neutralTertiary: "#c8c8c8",
        neutralSecondary: "#d0d0d0",
        neutralPrimaryAlt: "#dadada",
        neutralPrimary: "#ffffff",
        neutralDark: "#f4f4f4",
        black: "#f8f8f8",
        white: "#000000",
      },
    }),
  },
  [Themes.ContrastLight]: {
    localizedName: strings.ThemeContrastLight,
    themeId: Themes.ContrastLight,
    themeType: ThemeTypes.Light,
    theme: createTheme({
      palette: {
        themePrimary: "#000080",
        themeLighterAlt: "#f0f0fa",
        themeLighter: "#c5c5eb",
        themeLight: "#9898d9",
        themeTertiary: "#4747b3",
        themeSecondary: "#11118f",
        themeDarkAlt: "#000073",
        themeDark: "#000061",
        themeDarker: "#000047",
        neutralLighterAlt: "#f8f8f8",
        neutralLighter: "#f4f4f4",
        neutralLight: "#eaeaea",
        neutralQuaternaryAlt: "#dadada",
        neutralQuaternary: "#d0d0d0",
        neutralTertiaryAlt: "#c8c8c8",
        neutralTertiary: "#595754",
        neutralSecondary: "#373534",
        neutralPrimaryAlt: "#2f2d2c",
        neutralPrimary: "#000000",
        neutralDark: "#151413",
        black: "#0b0b0a",
        white: "#ffffff",
      },
    }),
  },
  [Themes.DeepSea]: {
    localizedName: strings.ThemeDeepSea,
    themeId: Themes.DeepSea,
    themeType: ThemeTypes.Dark,
    theme: createTheme({
      palette: {
        themePrimary: "#e8a63c",
        themeLighterAlt: "#090702",
        themeLighter: "#251b0a",
        themeLight: "#463212",
        themeTertiary: "#8b6424",
        themeSecondary: "#cc9235",
        themeDarkAlt: "#eaaf4e",
        themeDark: "#eeba68",
        themeDarker: "#f2cc8e",
        neutralLighterAlt: "#02132b",
        neutralLighter: "#041833",
        neutralLight: "#092141",
        neutralQuaternaryAlt: "#0e274a",
        neutralQuaternary: "#122c51",
        neutralTertiaryAlt: "#27456f",
        neutralTertiary: "#e8f6f6",
        neutralSecondary: "#ebf8f7",
        neutralPrimaryAlt: "#eff9f9",
        neutralPrimary: "#dcf2f1",
        neutralDark: "#f7fcfc",
        black: "#fbfdfd",
        white: "#000e21",
      },
    }),
  },
  [Themes.DefaultDark]: {
    localizedName: strings.ThemeDefaultDark,
    themeId: Themes.DefaultDark,
    themeType: ThemeTypes.Dark,
    theme: createTheme({
      palette: {
        themePrimary: "#00c8ff",
        themeLighterAlt: "#00080a",
        themeLighter: "#002029",
        themeLight: "#003c4d",
        themeTertiary: "#007899",
        themeSecondary: "#00b0e0",
        themeDarkAlt: "#19cdff",
        themeDark: "#3dd5ff",
        themeDarker: "#70e0ff",
        neutralLighterAlt: "#323130",
        neutralLighter: "#31302f",
        neutralLight: "#2f2e2d",
        neutralQuaternaryAlt: "#2c2b2a",
        neutralQuaternary: "#2a2928",
        neutralTertiaryAlt: "#282726",
        neutralTertiary: "#c8c8c8",
        neutralSecondary: "#d0d0d0",
        neutralPrimaryAlt: "#dadada",
        neutralPrimary: "#ffffff",
        neutralDark: "#f4f4f4",
        black: "#f8f8f8",
        white: "#323130",
      },
    }),
  },
  [Themes.DefaultLight]: {
    localizedName: strings.ThemeDefaultLight,
    themeId: Themes.DefaultLight,
    themeType: ThemeTypes.Light,
    theme: createTheme({
      palette: {
        themePrimary: "#00570e",
        themeLighterAlt: "#cfebd3",
        themeLighter: "#a7d8af",
        themeLight: "#83c68e",
        themeTertiary: "#63b370",
        themeSecondary: "#47a156",
        themeDarkAlt: "#2f8e3f",
        themeDark: "#1b7c2b",
        themeDarker: "#0c691b",
        neutralLighterAlt: "#f3f3f3",
        neutralLighter: "#efefef",
        neutralLight: "#e5e5e5",
        neutralQuaternaryAlt: "#d6d6d6",
        neutralQuaternary: "#cccccc",
        neutralTertiaryAlt: "#c4c4c4",
        neutralTertiary: "#a19f9d",
        neutralSecondary: "#605e5c",
        neutralPrimaryAlt: "#3b3a39",
        neutralPrimary: "#323130",
        neutralDark: "#201f1e",
        black: "#000000",
        white: "#fafafa",
      },
    }),
  },
  [Themes.EarthAndSky]: {
    localizedName: strings.ThemeEarthAndSky,
    themeId: Themes.EarthAndSky,
    themeType: ThemeTypes.Light,
    theme: createTheme({
      palette: {
        themePrimary: "#8f4700",
        themeLighterAlt: "#fbf6f0",
        themeLighter: "#eddac7",
        themeLight: "#ddbc9b",
        themeTertiary: "#bc834b",
        themeSecondary: "#9c5813",
        themeDarkAlt: "#814000",
        themeDark: "#6d3600",
        themeDarker: "#502800",
        neutralLighterAlt: "#e9f6f8",
        neutralLighter: "#e5f2f4",
        neutralLight: "#dce8ea",
        neutralQuaternaryAlt: "#cdd8da",
        neutralQuaternary: "#c4cfd0",
        neutralTertiaryAlt: "#bcc7c8",
        neutralTertiary: "#a19f9d",
        neutralSecondary: "#605e5c",
        neutralPrimaryAlt: "#3b3a39",
        neutralPrimary: "#323130",
        neutralDark: "#201f1e",
        black: "#000000",
        white: "#f0fdff",
      },
    }),
  },
  [Themes.MidnightEarth]: {
    localizedName: strings.ThemeMidnightEarth,
    themeId: Themes.MidnightEarth,
    themeType: ThemeTypes.Dark,
    theme: createTheme({
      palette: {
        themePrimary: "#d1ad7d",
        themeLighterAlt: "#080705",
        themeLighter: "#211c14",
        themeLight: "#3f3426",
        themeTertiary: "#7d684b",
        themeSecondary: "#b8986e",
        themeDarkAlt: "#d6b489",
        themeDark: "#dcbf99",
        themeDarker: "#e5cfb2",
        neutralLighterAlt: "#0b0b0b",
        neutralLighter: "#151515",
        neutralLight: "#252525",
        neutralQuaternaryAlt: "#2f2f2f",
        neutralQuaternary: "#373737",
        neutralTertiaryAlt: "#595959",
        neutralTertiary: "#e0e0e0",
        neutralSecondary: "#e5e5e5",
        neutralPrimaryAlt: "#eaeaea",
        neutralPrimary: "#d1d1d1",
        neutralDark: "#f4f4f4",
        black: "#f9f9f9",
        white: "#000000",
      },
    }),
  },
};
